// Rickshaw image URLs from GitHub repository
export const rickshawImages = [
  'https://raw.githubusercontent.com/Reysajju/SWA/main/img/swa-rickshaw%20(1).jpeg',
  'https://raw.githubusercontent.com/Reysajju/SWA/main/img/swa-rickshaw%20(2).jpeg',
  'https://raw.githubusercontent.com/Reysajju/SWA/main/img/swa-rickshaw%20(3).jpeg',
  'https://raw.githubusercontent.com/Reysajju/SWA/main/img/swa-rickshaw%20(4).jpeg',
  'https://raw.githubusercontent.com/Reysajju/SWA/main/img/swa-rickshaw%20(5).jpeg',
  'https://raw.githubusercontent.com/Reysajju/SWA/main/img/swa-rickshaw%20(6).jpeg',
  'https://raw.githubusercontent.com/Reysajju/SWA/main/img/swa-rickshaw%20(7).jpeg',
  'https://raw.githubusercontent.com/Reysajju/SWA/main/img/swa-rickshaw%20(8).jpeg',
  'https://raw.githubusercontent.com/Reysajju/SWA/main/img/swa-rickshaw%20(9).jpeg',
  'https://raw.githubusercontent.com/Reysajju/SWA/main/img/swa-rickshaw%20(10).jpeg',
  'https://raw.githubusercontent.com/Reysajju/SWA/main/img/swa-rickshaw%20(11).jpeg',
  'https://raw.githubusercontent.com/Reysajju/SWA/main/img/swa-rickshaw%20(12).jpeg',
  'https://raw.githubusercontent.com/Reysajju/SWA/main/img/swa-rickshaw%20(13).jpeg',
  'https://raw.githubusercontent.com/Reysajju/SWA/main/img/swa-rickshaw%20(14).jpeg',
  'https://raw.githubusercontent.com/Reysajju/SWA/main/img/swa-rickshaw%20(15).jpeg',
  'https://raw.githubusercontent.com/Reysajju/SWA/main/img/swa-rickshaw%20(16).jpeg',
  'https://raw.githubusercontent.com/Reysajju/SWA/main/img/swa-rickshaw%20(17).jpeg',
  'https://raw.githubusercontent.com/Reysajju/SWA/main/img/swa-rickshaw%20(18).jpeg',
  'https://raw.githubusercontent.com/Reysajju/SWA/main/img/swa-rickshaw%20(19).jpeg',
  'https://raw.githubusercontent.com/Reysajju/SWA/main/img/swa-rickshaw%20(20).jpeg',
  'https://raw.githubusercontent.com/Reysajju/SWA/main/img/swa-rickshaw%20(21).jpeg',
  'https://raw.githubusercontent.com/Reysajju/SWA/main/img/swa-rickshaw%20(22).jpeg',
  'https://raw.githubusercontent.com/Reysajju/SWA/main/img/swa-rickshaw%20(23).jpeg',
  'https://raw.githubusercontent.com/Reysajju/SWA/main/img/swa-rickshaw%20(24).jpeg',
  'https://raw.githubusercontent.com/Reysajju/SWA/main/img/swa-rickshaw%20(25).jpeg',
  'https://raw.githubusercontent.com/Reysajju/SWA/main/img/swa-rickshaw%20(26).jpeg',
  'https://raw.githubusercontent.com/Reysajju/SWA/main/img/swa-rickshaw%20(27).jpeg',
  'https://raw.githubusercontent.com/Reysajju/SWA/main/img/swa-rickshaw%20(28).jpeg',
  'https://raw.githubusercontent.com/Reysajju/SWA/main/img/swa-rickshaw%20(29).jpeg'
].map(url => url.replace(/ /g, '%20'));